name: tests-auth
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" > .npmrc && npm install && npm run test:ci
