name: tests-order
on:
  pull_request:
    paths:
      - 'order/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd order && echo "//npm.pkg.github.com/:_authToken=${{ secrets.TOKEN }}" > .npmrc && npm install && npm run test:ci
